version: '3.8'

volumes:
  post-storage: {}

networks:
  default-network:
    driver: bridge

services:

  post-service:
    container_name: post-service
    depends_on:
      post-service-storage-migrate:
        condition: service_completed_successfully
      kafka:
        condition: service_healthy
    build:
        dockerfile: Dockerfile
    environment:
      - GRPC_HOST=0.0.0.0
      - GRPC_PORT=5050
      - HTTP_HOST=0.0.0.0
      - HTTP_PORT=5959
      - LOG_LVL=info
      - STORAGE_HOST=post-service-storage
      - STORAGE_PORT=5432
      - STORAGE_USER=postgres
      - STORAGE_PASSWORD=password
      - POST_DB_NAME=posts
      - KAFKA_HOST=kafka
      - KAFKA_PORT=9092
    ports:
      - "5050:5050"
      - "5959:5959"
    networks:
      - default-network

  post-service-storage:
    image: postgres:alpine
    container_name: post-service-storage
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 2s
      timeout: 1s
      retries: 5
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - post-storage:/var/lib/postgresql/data
    networks:
      - default-network

  post-service-storage-migrate:
    image: migrate/migrate:v4.15.2 # Image page: <https://hub.docker.com/r/migrate/migrate>
    container_name: post-service-storage-migrate
    volumes: [ .:/src:ro ]
    working_dir: /src
    entrypoint: migrate -database "postgres://postgres:password@post-service-storage:5432/posts?sslmode=disable" -source file://./migrations -verbose up
    depends_on:
      post-service-storage:
        condition: service_healthy
    networks:
      - default-network

  zookeeper:
    hostname: zookeeper
    image: wurstmeister/zookeeper:3.4.6
    networks:
      - default-network

  kafka:
    image: wurstmeister/kafka
    env_file:
      - config/kafka-variables.env
    depends_on:
      - zookeeper
    healthcheck:
      test: nc -z localhost 9092 || exit -1
      start_period: 5s
      interval: 5s
      timeout: 10s
      retries: 10
    networks:
      - default-network
