version: '3.8'

networks:
  integration-tests:
    driver: bridge

services:

  post-service-test:
    container_name: post-service-test
    depends_on:
      post-service-storage-test:
        condition: service_healthy
    build:
      dockerfile: test.Dockerfile
    environment:
      - GRPC_HOST=0.0.0.0
      - GRPC_PORT=6060
      - LOG_LVL=info
      - STORAGE_HOST=post-service-storage-test
      - STORAGE_PORT=5432
      - STORAGE_USER=postgres
      - STORAGE_PASSWORD=postgres
      - USER_DB_NAME=postgres
      - USER_TABLE_NAME=users_test
      - CITY_TABLE_NAME=city_test
      - INTEREST_TABLE_NAME=interest_test
      - USER_PER_INTEREST_TABLE_NAME=user_per_interest_test
      - KAFKA_ENABLE=false
    networks:
      - integration-tests

  post-service-storage-test:
    image: postgres:latest
    container_name: post-service-storage-test
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 2s
      timeout: 1s
      retries: 5
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - integration-tests
