// Code generated by mockery v2.24.0. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	model "gitlab.com/pet-pr-social-network/post-service/internal/model"
)

// PostMsgSender is an autogenerated mock type for the PostMsgSender type
type PostMsgSender struct {
	mock.Mock
}

// SendMsgPostCreated provides a mock function with given fields: post
func (_m *PostMsgSender) SendMsgPostCreated(post model.Post) {
	_m.Called(post)
}

// SendMsgPostDeleted provides a mock function with given fields: id, userID
func (_m *PostMsgSender) SendMsgPostDeleted(id int64, userID int64) {
	_m.Called(id, userID)
}

type mockConstructorTestingTNewPostMsgSender interface {
	mock.TestingT
	Cleanup(func())
}

// NewPostMsgSender creates a new instance of PostMsgSender. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewPostMsgSender(t mockConstructorTestingTNewPostMsgSender) *PostMsgSender {
	mock := &PostMsgSender{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
